name: Victory Formation
url: "http://lyzidiamond.com"
description: Lyzi Diamond writes on the internet sometimes.
permalink: /:categories/:title
markdown: kramdown
exclude:
- package.json
- node_modules
kramdown:
  auto_ids:       true
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
